### PR TITLE
[mqtt] fix compilation error

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes a null-type mismatch introduced with #6239 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by martinvw** [comment]
@davidgraeff any objections here?

**Comment by davidgraeff** [comment]
I resisted on commenting this change. It fixes something after all. Thanks Jan!

But now that Martin pushed this PR into my attention once again: I consider the transformation code path, a hot path. (As hot as java can get at least ;). And this PR introduces a conditional check and a log statement per loop iteration.

And I'm also not sure if this is the right place to add those log statements. If another generic binding like the http2 binding want to offer chainable transformations as well: Do they need to add logs as well? Or do they discard failed transformed values? I see the potential that inconsistencies appear.

All in all: This PR fixes a problem and should probably be merged, but I'm not really happy with it.

**Comment by martinvw** [comment]
Fair point, I think that the null check is cheap but logging to info on something which might happen continuously sounds indeed not optimal. Thanks!

**Comment by J-N-K** [comment]
The same is true for the inbound transformation, right? Reduce both logs to debug or discard without notice?
